---
- name: Validate Inventory
  when: not (inventory_validated | default(False) | bool)
  delegate_to: "{{ validation_host | default('bastion') }}"
  block:
    - name: Check required vars
      ansible.builtin.include_tasks:
        file: required_vars.yml
        apply:
          tags: validate_required_vars
      tags: validate_required_vars

    - name: Check cluster values
      ansible.builtin.include_tasks:
        file: cluster.yml
        apply:
          tags: validate_cluster
      tags: validate_cluster

    - name: Check vendor vars
      ansible.builtin.include_tasks:
        file: vendor.yml
        apply:
          tags: validate_vendor
      tags: validate_vendor

    - name: Check ntp vars
      ansible.builtin.include_tasks:
        file: ntp.yml
        apply:
          tags: validate_ntp
      tags: validate_ntp

    - name: Check VM vars
      ansible.builtin.include_tasks:
        file: vms.yml
        apply:
          tags: validate_vms
      tags: validate_vms

    - name: Check secrets
      ansible.builtin.include_tasks:
        file: secrets.yml
        apply:
          tags: validate_secrets
      tags: validate_secrets

    - name: Check prereqs
      ansible.builtin.include_tasks:
        file: prereqs.yml
        apply:
          tags: validate_prereqs
      tags: validate_prereqs

    - name: Check proxy vars
      ansible.builtin.include_tasks:
        file: proxy.yml
        apply:
          tags: validate_proxy_config
      tags: validate_proxy_config

    - name: Check network vars
      ansible.builtin.include_tasks:
        file: network.yml
        apply:
          tags: validate_network
      tags: validate_network

    - name: Check day2 vars
      ansible.builtin.include_tasks:
        file: day2.yml
        apply:
          tags: validate_day2
      tags: validate_day2

    - name: Check partitions vars
      ansible.builtin.include_tasks:
        file: partitions.yml
        apply:
          tags: validate_partitions
      tags: validate_partitions

    - name: Check pxe vars
      ansible.builtin.include_tasks:
        file: validate_pxe.yml
        apply:
          tags: validate_pxe
      tags: validate_pxe
      when: (setup_pxe_service | default(false)) | bool

    - name: Check installer feature gates
      ansible.builtin.include_tasks:
        file: agent_based_installer_feature_gates.yml
        apply:
          tags: validate_agent_based_installer
      when:
        - (use_agent_based_installer | default(true) | bool)
        - not ((ignore_agent_based_installer_feature_gates | default(false)) | bool)
      tags: validate_agent_based_installer

    - name: Check agent based installer requirements
      ansible.builtin.include_tasks:
        file: agent_based_installer_requirements.yml
        apply:
          tags: validate_agent_based_installer
      when:
        - (use_agent_based_installer | default(true) | bool)
      tags: validate_agent_based_installer


- name: Record successful validation on all hosts
  ansible.builtin.set_fact:
    inventory_validated: true
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['all'] + ['localhost'] }}"
