---
- name: Validate Inventory
  block:
    - include_tasks:
        file: required_vars.yml
        apply:
          tags: validate_required_vars
          delegate_to: bastion
      tags: validate_required_vars

    - include_tasks:
        file: cluster.yml
        apply:
          tags: validate_cluster
          delegate_to: bastion
      tags: validate_cluster

    - include_tasks:
        file: secrets.yml
        apply:
          tags: validate_secrets
      tags: validate_secrets

    - include_tasks:
        file: prereqs.yml
        apply:
          tags: validate_prereqs
          delegate_to: bastion
      tags: validate_prereqs

    - include_tasks:
        file: network.yml
        apply:
          tags: validate_network
          delegate_to: bastion
      tags: validate_network

    - include_tasks:
        file: day2.yml
        apply:
          tags: validate_day2
          delegate_to: bastion
      tags: validate_day2

  when: not (inventory_validated | default(False) | bool)

- name: Record successful validation on all hosts
  set_fact:
    inventory_validated: True
  delegate_to: "{{ item }}"
  delegate_facts: True
  loop: "{{ groups['all'] + ['localhost'] }}"
