---
- name: Validate Inventory
  block:
    - import_role:  # noqa unnamed-task
        name: validations/required_vars
      tags: validate_required_vars

    - import_role:  # noqa unnamed-task
        name: validations/cluster
      tags: validate_cluster

    - import_role:  # noqa unnamed-task
        name: validations/vendor
      tags: validate_vendor

    - import_role:  # noqa unnamed-task
        name: validations/ntp
      tags: validate_ntp

    - import_role:  # noqa unnamed-task
        name: validations/vms
      tags: validate_vms

    - import_role:  # noqa unnamed-task
        name: validations/secrets
      tags: validate_secrets

    - import_role:  # noqa unnamed-task
        name: validations/prereqs
      tags: validate_prereqs

    - import_role:  # noqa unnamed-task
        name: validations/network
      tags: validate_network

    - import_role:  # noqa unnamed-task
        name: validations/day2
      tags: validate_day2

    - import_role:  # noqa unnamed-task
        name: validations/partitions
      tags: validate_partitions

    - import_role:  # noqa unnamed-task
        name: validations/pxe
      tags: validate_pxe