---
- name: Validate Inventory
  block:
    - include_role:  # noqa unnamed-task
        name: validations/required_vars
        apply:
          tags: validate_required_vars
      tags: validate_required_vars

    - include_role:  # noqa unnamed-task
        name: validations/cluster
        apply:
          tags: validate_cluster
      tags: validate_cluster

    - include_role:  # noqa unnamed-task
        name: validations/vendor
        apply:
          tags: validate_vendor
      tags: validate_vendor

    - include_role:  # noqa unnamed-task
        name: validations/ntp
        apply:
          tags: validate_ntp
      tags: validate_ntp

    - include_role:  # noqa unnamed-task
        name: validations/vms
        apply:
          tags: validate_vms
      tags: validate_vms

    - include_role:  # noqa unnamed-task
        name: validations/secrets
        apply:
          tags: validate_secrets
      tags: validate_secrets

    - include_role:  # noqa unnamed-task
        name: validations/prereqs
        apply:
          tags: validate_prereqs
      tags: validate_prereqs

    - include_role:  # noqa unnamed-task
        name: validations/network
        apply:
          tags: validate_network
      tags: validate_network

    - include_role:  # noqa unnamed-task
        name: validations/day2
        apply:
          tags: validate_day2
      tags: validate_day2

    - include_role:  # noqa unnamed-task
        name: validations/partitions
        apply:
          tags: validate_partitions
      tags: validate_partitions

    - include_role:  # noqa unnamed-task
        name: validations/pxe
        apply:
          tags: validate_pxe
      tags: validate_pxe
      when: (setup_pxe_service | default(false)) | bool

  when: not (inventory_validated | default(False) | bool)
  delegate_to: "{{ validation_host | default('bastion') }}"

- name: Record successful validation on all hosts
  set_fact:
    inventory_validated: True
  delegate_to: "{{ item }}"
  delegate_facts: True
  loop: "{{ groups['all'] + ['localhost'] }}"
