---
# tasks file for create_cluster

- name: Create cluster
  uri:
    url: "{{ URL_ASSISTED_INSTALLER_CLUSTERS }}"
    method: POST
    url_username: "{{ HTTP_AUTH_USERNAME }}"
    url_password: "{{ HTTP_AUTH_PASSWORD }}"
    body_format: json
    status_code: [201]
    return_content: True
    # - `ingress_vip` is not provided in the request body because the value
    #   can't be set for SNO with user-managed networking enabled.
    #   HA clusters will be patched with the `ingress_vip` setting during
    #   the execution of the `install_cluster` role.
    # - the request body is wrapped in a jinja2 expression with the `to_json`
    #   filter to prevent the `cluster_network_host_prefix` value from being
    #   type casted to a string. The Assisted Installer API requires this
    #   input field to be an integer.
    body: >-
      {{ {
        "name": cluster_name,
        "high_availability_mode": (high_availability_mode | title),
        "openshift_version": (openshift_version | string),
        "base_dns_domain": base_dns_domain,
        "cluster_network_cidr": cluster_network_cidr,
        "cluster_network_host_prefix": (cluster_network_host_prefix | int),
        "service_network_cidr": service_network_cidr,
        "pull_secret": (pull_secret | to_json),
        "ssh_public_key": ssh_public_key,
        "vip_dhcp_allocation": (vip_dhcp_allocation | lower | bool),
        "api_vip": api_vip,
        "http_proxy": http_proxy,
        "https_proxy": https_proxy,
        "no_proxy": no_proxy,
        "additional_ntp_source": ntp_server,
      } | to_json }}
  when: create | bool == True
  register: http_reply

## Add stuff for 
# "network_type":
# "schedulable_masters":
# "disk_encryption"???


- debug: # noqa unnamed-task
    var: http_reply.json
    verbosity: 1
  when: create | bool == True

- name: Set the cluster ID
  set_fact:
    cluster_id: "{{ http_reply.json.id }}"
  when: create | bool == True

- name: "Save cluster_id"
  copy:
    content: "{{ cluster_id }}"
    dest: "{{ fetched_dest }}/cluster.txt"
    mode: 0644
  delegate_to: localhost
  become: no
  when: create | bool == True
