---
- import_playbook: prereq_facts_check.yml

- name: Play to populate image_hashes for relevant images
  hosts: localhost
  roles:
    - get_image_hash

- import_playbook: playbooks/deploy_ntp.yml

- import_playbook: playbooks/deploy_registry.yml

- import_playbook: playbooks/deploy_dns.yml

- import_playbook: playbooks/deploy_assisted_installer_onprem.yml

- import_playbook: playbooks/create_vms.yml
  vars:
    SETUP_VMS: "{{ setup_vms | default(true) }}"
  when: SETUP_VMS == True

- import_playbook: playbooks/deploy_sushy_tools.yml
  vars:
    SETUP_SUSHY_TOOLS: "{{ setup_sushy_tools | default(setup_vms | default(True)) }}"
  when: SETUP_SUSHY_TOOLS == True
