- name: Wait for cluster to come up 
  wait_for:
    host: "{{ api_vip }}"
    port: 6443
    timeout: 3600
    sleep: 60

- name: oc stuff
  environment:
    KUBECONFIG: "{{ cluster_manifest_parent_dir }}/auth/kubeconfig"
  block:
    - name: Wait for up to 30 mins to login as kubeadmin
      shell:
        cmd: "oc login --insecure-skip-tls-verify=true -u kubeadmin -p '{{ kubeadmin_password }}'"
      register: login_result
      until: ('Login successful.' in login_result.stdout)
      retries: 60
      delay: 30

    - name: Check status of cluster operators
      block:
        - name: Wait up to 20 mins for cluster to become functional
          shell:
            cmd: oc wait clusteroperators --all --for=condition=Available --timeout=20m
      rescue:
        - name: Get better info for failure message
          shell: oc get clusteroperators
          register: co_result

        - fail:  # noqa unnamed-task
            msg: |
              Cluster has not come up correctly:
                {{ co_result.stdout }}

    - name: Get clusterversion after login
      vars:
        expected_message: "Cluster version is {{ openshift_full_version }}"
      shell:
        cmd: "oc get clusterversion"      
      register: clusterversion
      until: expected_message in clusterversion.stdout
      retries: 60
      delay: 30