# - name: Create podman auth dir
#   file:
#     path: "{{ config_file_path }}/containers/"
#     state: directory
#     mode: 0755
#     recurse: true


- name: Create podman auth dir
  file:
    path: "{{ ansible_env.HOME }}/.docker"
    state: directory
    mode: 0755
    recurse: true


# - name: Copy pull_secret file.
#   copy:
#     content: "{{ pull_secret }}"
#     dest: "{{ config_file_path }}/containers/auth.json"
#     mode: 0644

- name: Copy pull_secret file.
  copy:
    content: "{{ pull_secret }}"
    dest: "{{ ansible_env.HOME }}/.docker/config.json"
    mode: 0644

- name: Login and generate iso
  environment:
    XDG_RUNTIME_DIR: "{{ config_file_path }}"
    REGISTRY_AUTH_FILE: "{{ config_file_path }}/containers/auth.json"
  block:
    - debug:
        var: config_file_path

    # - name: Podman login to remote registry
    #   containers.podman.podman_login_info:
    #     registry: "registry.redhat.io"

    - name: Generate iso
      ansible.builtin.shell:
        cmd: "{{ billi_executable }} --log-level=debug agent create image"
        chdir: "{{ cluster_manifest_parent_dir }}"
      environment:
        OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: "{{ (release_images_defaults |json_query(version_filter))[0].url }}"

- name: Put discovery iso in http store
  block:
    - name: Create discovery directory
      file:
        path: "{{ download_dest_path + '/' + download_agent_dest_file | dirname }}"
        recurse: yes
        state: directory

    - name: Create discovery directory
      ansible.builtin.copy:
        src: "{{ cluster_manifest_parent_dir }}/agent.iso"
        dest: "{{ download_dest_path + '/' + download_agent_dest_file }}"
        mode: 0644
  delegate_to: http_store
  become: true
