node_required_vars:
  - bmc_password
  - bmc_user
  - vendor
  - role
  - mac

supported_role_values:
  - worker
  - master

supported_vendor_values:
  - dell
  - hpe
  - lenovo
  - kvm
  - supermicro
  - pxe
  - zt

allow_custom_vendor: false

ai_version: "{{ hostvars.assisted_installer.ai_version | default('v2.26.0') }}"
ai_version_number: "{{ ai_version | regex_replace('v(\\d+\\.\\d+\\.\\d+)', '\\1') }}"

single_node_openshift_enabled: "{{ is_valid_single_node_openshift_config | default(false) }}"
