node_required_vars:
  - bmc_address
  - bmc_password
  - bmc_user
  - vendor
  - role
  - mac

supported_role_values:
  - worker
  - master

supported_vendor_values:
  - dell
  - hpe
  - lenovo
  - kvm
  - supermicro

ai_version: "{{ hostvars.assisted_installer.ai_version | default('v2.1.1') }}"
ai_version_number: "{{ ai_version | regex_replace('v(\\d+\\.\\d+.\\d+', '\\1') }}"

supported_ocp_versions:
  - 4.6.16
  - 4.7.33
  - 4.8.14
  - 4.9.0
  - 4.9.11

single_node_openshift_enabled: "{{ is_valid_single_node_openshift_config | default(false) }}"
