generated_dir: "{{ repo_root_path }}/generated"
cluster_manifest_parent_dir: "{{ generated_dir}}/{{ cluster_name }}"
assisted_installer_ip_regex: "SERVICE_BASE_URL.*http://(((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])):8090"

kube_filename: "{{ kubeconfig_dest_filename | default(cluster_name + '-kubeconfig') }}"
dest_dir: "{{ kubeconfig_dest_dir | default(ansible_env.HOME) }}"
kubeconfig_path: "{{ dest_dir }}/{{ kube_filename }}"
kubeadmin_vault_name: "{{ kubeadmin_dest_filename | default(cluster_name +'-kubeadmin.vault.yml') }}"