- name: Get Systems
  community.general.redfish_info:
    category: Systems
    command: GetSystemInventory
    baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
    username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
  register: res

- name: Set system id
  set_fact:
    system_id: "{{ (res.redfish_facts.system | json_query(query))[0].id }}"
  vars:
    query: "entries[*][?Name==`{{ inventory_hostname }}`][].{id: Id}"

- name: KVM Power Off
  community.general.redfish_command:
    category: Systems
    command: PowerForceOff
    baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
    username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
    resource_id: "{{ system_id }}"

- name: Set KVM OneTimeBoot VirtualCD (Cd)
  community.general.redfish_command:
    category: Systems
    command: SetOneTimeBoot
    bootdevice: Cd
    baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
    username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
    resource_id: "{{ system_id }}"

- name: KVM Eject Virtual Media (if any)
  community.general.redfish_command:
    category: Manager
    command: VirtualMediaEject
    baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
    username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
    virtual_media:
      image_url: "{{ discovery_iso_name.split('/')[-1] }}"
      inserted: false
    resource_id: "{{ system_id }}"
  ignore_errors: yes

- name: KVM Insert Virtual Media
  community.general.redfish_command:
    category: Manager
    command: VirtualMediaInsert
    baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
    username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
    virtual_media:
      image_url: "{{ boot_iso_url }}"
      media_types:
        - CD
    resource_id: "{{ system_id }}"
    timeout: 30
  register: inserted
  vars:
    boot_iso_url: "{{ discovery_iso_server }}/{{ discovery_iso_name }}"
    discovery_iso_server: http://registry.cars.lab

- name: KVM Restart system power gracefully
  community.general.redfish_command:
    category: Systems
    command: PowerOn
    baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
    username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
    password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
    resource_id: "{{ system_id }}"
