---
- name: Setup AI
  become: True
  block:
    - name: Install podman
      package:
        name: podman
        state: present

    - name: "Build assisted_service_openshift_versions ({{ item }})"
      vars:
        assisted_service_openshift_versions: {}
        assisted_installer_os_images: []
        assisted_installer_release_images: []
      set_fact:
        assisted_installer_os_images: "{{ assisted_installer_os_images + assisted_installer_os_images_defualts[item] }}"
        assisted_installer_release_images: "{{ assisted_installer_release_images + assisted_installer_release_images_defaults[item] }}"
      loop: "{{ ocp_release_versions }}"

    - name: Open ports zone internal and public, for firewalld
      firewalld:
        port: "{{ item.1 }}/tcp"
        permanent: yes
        immediate: yes
        state: enabled
        zone: "{{ item.0 }}"
      loop: "{{ ['internal', 'public'] | product(['8000', '8090', '8080', '8888']) | list }}"

    - name: Create directories for assisted-installer
      file:
        path: "{{ item }}"
        mode: 0775
        state: directory
      with_items:
        - "{{ assisted_installer_dir }}"
        - "{{ assisted_installer_dir }}/data"

    - name: Create directory for assisted-installer database
      file:
        path: "{{ assisted_installer_dir }}/data/postgresql"
        mode: 0775
        state: directory
        recurse: true
  
    - name: Template out assisted-installer files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 0644
        trim_blocks: true
        lstrip_blocks: true
      loop:
        - src: configmap.yml.j2
          dest: "{{ assisted_installer_dir }}/configmap.yml"
        - src: pod.yml.j2
          dest: "{{ assisted_installer_dir }}/pod.yml"

    - name: Gather info about specific pods
      containers.podman.podman_pod_info:
        name: assisted-installer
      register: ai_pod_details
    
    - name: Remove Assisted Installer Pod
      containers.podman.podman_pod:
        name: assisted-installer
        state: absent
      when: (ai_pod_details.pods | length) > 0 
    
    - name: Play kube file
      containers.podman.podman_play:
        kube_file: "{{ assisted_installer_dir }}/pod.yml"
        configmap: "{{ assisted_installer_dir }}/configmap.yml"
        recreate: true
        state: created

- name: Setup assisted_installer service
  become: true
  block:
    - name: Copy the systemd service file
      copy:
        content: |
          [Unit]
          Description=Podman assisted_installer.service
          [Service]
          Restart=no
          ExecStart=/usr/bin/podman pod start assisted-installer
          ExecStop=/usr/bin/podman pod stop -t 10 assisted-installer
          KillMode=none
          Type=forking
          [Install]
          WantedBy=default.target
        dest: "/etc/systemd/system/assisted_installer.service"
        mode: 0644

    - name: Reload systemd service
      systemd:
        daemon_reexec: yes
        scope: system

    - name: Enable assisted_installer.service
      systemd:
        name: assisted_installer
        enabled: yes
        scope: system

    - name: Start assisted_installer.service
      systemd:
        name: assisted_installer
        state: started
        scope: system
