---
# tasks file for monitor_cluster

- name : Get get hosts status during installation
  uri:
    url: "{{ URL_ASSISTED_INSTALLER_CLUSTER }}/hosts?with-inventory=1"
    method: GET
    status_code: [200, 201]
    return_content: True
  register: cluster_hosts
  delegate_to: bastion

- name: Find host
  set_fact:
    current_host: "{{ item }}"
  when: (mac | upper) in ((item.inventory | from_json).interfaces | flatten | map(attribute='mac_address') | map('upper') | list )
  loop: "{{ cluster_hosts.json }}"

- debug: # noqa unnamed-task
    msg: "{{ current_host }}"
    verbosity: 1

- name: Start host monitoring
  include_tasks: hosts_monitoring.yml
  args:
    apply:
      delegate_to: bastion
  vars:
    host_id: "{{ current_host.id }}"
    host_name: "{{ inventory_hostname }}"
  no_log: True
