api_vips: "{% if extra_api_vip is defined %}{{ [api_vip, extra_api_vip] }}{% else %}{{ [api_vip] }}{% endif %}"
ingress_vips: "{% if extra_ingress_vip is defined %}{{ [ingress_vip, extra_ingress_vip] }}{% else %}{{ [ingress_vip] }}{% endif %}"

required_domains:
  "api": "api.{{ domain }}"
  "api-int": "api-int.{{ domain }}"
  "apps": "*.apps.{{ domain }}"

expected_answers:
  "api": "{{ api_vips }}"
  "api-int": "{{ api_vips }}"
  "apps": "{{ ingress_vip }}"

required_binary: dig
required_binary_provided_in_package: bind-utils
domain: "{{ cluster_name }}.{{ base_dns_domain }}"
