---
- name: Validate Inventory
  ansible.builtin.import_playbook: validate_inventory.yml

- name: Approve CSRs on cluster
  hosts: bastion
  gather_facts: false
  roles:
    - role: redhatci.ocp.approve_csrs
      when: groups['day2_workers'] | default([]) | length > 0
