---
# file: boot_disk.yml
- name: Validate Inventory
  ansible.builtin.import_playbook: validate_inventory.yml

- name: Unmounting Assisted Installer Discovery ISO
  hosts: bastion
  gather_facts: false
  roles:
    - redhatci.ocp.boot_disk
