---

- name: Process KVM nodes
  hosts: bastion
  roles:
    - role: process_kvm_nodes
      when: (setup_vms | default(true))

- name: Destroy VMS
  hosts: vm_hosts
  vars:
    SETUP_VMS: "{{ setup_vms | default((kvm_nodes | default([])) | length | int >= 1) }}"
  roles:
    - role: destroy_vms
      when: SETUP_VMS | bool
      tags:
        - destroy_vms

- import_playbook: configure_vm_host_network.yml

- name: Provision VMS
  hosts: vm_hosts
  vars:
    SETUP_VMS: "{{ setup_vms | default((kvm_nodes | default([])) | length | int >= 1) }}"
  roles:
    - role: create_vms
      when: SETUP_VMS | bool
      tags:
        - setup_vms
