---
- name: Validate Inventory
  ansible.builtin.import_playbook: validate_inventory.yml

- name: Create cluster and generate Assisted Installer Discovery ISO
  hosts: bastion
  gather_facts: false
  roles:
    - redhatci.ocp.create_cluster
    - redhatci.ocp.patch_cluster
