---
- name: Play to populate image_hashes for relevant images
  hosts: localhost
  vars:
    destination_hosts:
      - registry_host
  roles:
    - role: get_image_hash
      when: image_hashes | default({}) | length == 0

- name: Play to install and setup mirror registry
  hosts: registry_host
  vars:
    downloads_path: /tmp/wip
    config_file_path: /tmp/wip/config
    SETUP_REGISTRY_SERVICE: "{{ setup_registry_service | default(True)}}"
  roles:
    - role: setup_selfsigned_cert
      when: SETUP_REGISTRY_SERVICE == True
    - role: setup_mirror_registry
      when: SETUP_REGISTRY_SERVICE == True
    - role: populate_mirror_registry
      when: SETUP_REGISTRY_SERVICE == True
  collections:
    - containers.podman
    - community.crypto
    - community.general
    - ansible.posix
