---
- name: Validate Inventory
  ansible.builtin.import_playbook: validate_inventory.yml

- name: Play to populate image_hashes for relevant images
  hosts: localhost
  vars:
    destination_hosts:
      - assisted_installer
  pre_tasks:
    - name: Pre-compute need to get hashes
      ansible.builtin.set_fact:
        run_get_hash: "{{ image_hashes | default({}) | length == 0 }}"
  roles:
    - role: redhatci.ocp.get_image_hash
      when: run_get_hash

- name: Deploy OpenShift Assisted Installer On Prem
  hosts: assisted_installer
  roles:
    - role: redhatci.ocp.setup_assisted_installer
      when: SETUP_ASSISTED_INSTALLER | bool
  vars:
    SETUP_ASSISTED_INSTALLER: "{{ setup_assisted_installer | default(true) }}"
  post_tasks:
    # This should be moved into the role.
    - name: Wait for up to 60 minutes for the assisted installer to come online
      ansible.builtin.uri:
        url: "http://{{ ansible_host }}:8090/ready"
        method: GET
        status_code: [200, 201]
      register: result
      until: result is succeeded
      retries: 120
      delay: 30
      delegate_to: bastion
      when: SETUP_ASSISTED_INSTALLER | bool

    - name: Wait for up to 60 minutes for the assisted installer image service to come online
      ansible.builtin.uri:
        url: "http://{{ ansible_host }}:8888/health"
        method: GET
        status_code: [200, 201]
      register: result
      until: result is succeeded
      retries: 120
      delay: 30
      delegate_to: bastion
      when: SETUP_ASSISTED_INSTALLER | bool
