- name: Setup DNS Records
  hosts: dns_host
  gather_facts: False
  vars:
    SETUP_DNS_SERVICE: "{{ setup_dns_service | default(True) }}"
  pre_tasks:
    - name: Setup facts
      setup:
      when: SETUP_DNS_SERVICE == True
  roles:
    - role: redhatci.ocp.insert_dns_records
      when: SETUP_DNS_SERVICE == True
    - role: redhatci.ocp.validate_dns_records
