---
- import_playbook: playbooks/process_kvm_nodes.yml

- name: Deploy sushy tools
  hosts: vm_hosts
  gather_facts: False
  vars:
    SETUP_SUSHY_TOOLS:  "{{setup_sushy_tools | default((setup_vms | default((kvm_nodes | default([])) | length | int >= 1))) | bool }}"
  pre_tasks:
    - name: Setup facts
      setup:
      when: SETUP_SUSHY_TOOLS == True
  roles:
    - name: setup_sushy_tools
      when: SETUP_SUSHY_TOOLS | bool