---
- name: Validate Inventory
  ansible.builtin.import_playbook: validate_inventory.yml

- name: Setup TFTP
  hosts: tftp_host
  vars:
    SETUP_TFTP_SERVICE: "{{ setup_pxe_service | default(false) }}"
  roles:
    - role: redhatci.ocp.setup_tftp
      when: SETUP_TFTP_SERVICE | bool
