- name: Setup NTP
  hosts: ntp_host
  gather_facts: false
  vars:
    SETUP_NTP_SERVICE: "{{setup_ntp_service | default(true)}}"
  pre_tasks:
    - name: Setup facts
      ansible.builtin.set_fact:
      when: SETUP_NTP_SERVICE | bool
  roles:
    - role: redhatci.ocp.setup_ntp
      when: SETUP_NTP_SERVICE | bool
