---
- name: Validate Inventory
  ansible.builtin.import_playbook: validate_inventory.yml

- name: Extract openshift installer
  hosts: bastion
  gather_facts: false
  vars:
    destination_hosts:
      - bastion
  pre_tasks:
    - name: Pre-compute need to get hashes
      ansible.builtin.set_fact:
        run_get_hash: "{{ assisted_installer_release_images | default({}) | length == 0 }}"
  roles:
    - role: redhatci.ocp.get_image_hash
      when: run_get_hash | bool
    - redhatci.ocp.extract_openshift_installer
