---
- name: Validate Inventory
  ansible.builtin.import_playbook: validate_inventory.yml

- name: Generate agent iso using agent_based_installer
  hosts: bastion
  roles:
    - redhatci.ocp.generate_agent_iso
