---
- name: Validate Inventory
  ansible.builtin.import_playbook: validate_inventory.yml

- name: Monitoring hosts installation
  hosts: masters, workers
  gather_facts: false
  strategy: ansible.builtin.free
  roles:
    - redhatci.ocp.monitor_host
