---
- name: Validate Inventory
  ansible.builtin.import_playbook: validate_inventory.yml

- name: Mount discovery ISO for PXE
  hosts: http_store
  vars:
    MOUNT_DISCOVERY_ISO: "{{ (setup_pxe_service | default(false)) | bool }}"
  roles:
    - role: redhatci.ocp.mount_discovery_iso_for_pxe
      when: MOUNT_DISCOVERY_ISO | bool
