- name: Check if local_registry is in pull_secret
  set_fact:
    missing_registry_secret: "{{ local_registry not in pull_secret['auths'] }}"

- name: Add registry_key too pull_secret
  when: (missing_registry_secret or setup_registry_service)
  block:
    - name: Create config_file_path dir
      file:
        path: "{{ config_file_path }}"
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: 0775
        state: directory

    - name: Generate htpasswd entry
      command: htpasswd -bBn {{ disconnected_registry_user }} {{ disconnected_registry_password }}
      register: htpass_entry
      changed_when: false

    - name: Set disconnected_auth
      set_fact:
        disconnected_registry_up: "{{ disconnected_registry_user }}:{{ disconnected_registry_password }}"

    - name: Update pull_secret variable
      set_fact:
        pull_secret: "{{ pull_secret | combine({
          'auths': pull_secret['auths'] | combine({
            local_registry: {
              'auth': disconnected_registry_up | b64encode,
              'email': registry_email
            }
          })}
          ) }}"

    - name: Write updated pull_secret
      copy:
        content: "{{ pull_secret | to_json }}"
        dest: "{{ config_file_path }}/{{ pull_secret_file_name }}"
        mode: 0644

    - name: Update bastion
      set_fact:
        pull_secret: "{{ pull_secret }}"
      delegate_to: bastion
      delegate_facts: True
